version: '3.8'

services:
  cds-client:
    build: ./client
    image: cds-client:latest
    ports:
      - '8080:3000'
    restart: always
    networks:
      - default

  cds-server:
    build: ./server
    image: cds-server:latest
    restart: always
    ports:
      - 4000:4000
networks:
  default:
      name: sample
