apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
    - protocol: TCP
      name: server
      port: 4000
      targetPort: 4000
  type: LoadBalancer